version: '2'
services:
  cranberry:
    image: erikperkins/cranberry
    restart: on-failure
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_DATABASE: ${REDIS_DATABASE}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_MESSAGE_TTL: ${RABBITMQ_MESSAGE_TTL}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_ACCESS_SECRET: ${TWITTER_ACCESS_SECRET}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_TRACK: ${TWITTER_TRACK}
    ports:
      - 8000:80
